# Generated by Django 5.1.7 on 2025-04-27 09:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Department name', max_length=100)),
                ('code', models.CharField(help_text='Department code (e.g., CS, ENG)', max_length=10, unique=True)),
                ('department_head', models.OneToOneField(blank=True, help_text='Professor who is the head of this department', limit_choices_to={'user_type': 'department_head'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='headed_department', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Department',
                'verbose_name_plural': 'Departments',
                'ordering': ['code'],
            },
        ),
    ]
