# Generated by Django 5.1.7 on 2025-05-12 11:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('departments', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='department',
            name='total_laboratory_hours',
            field=models.PositiveIntegerField(default=0, editable=False, help_text='Total laboratory hours assigned from all curricula'),
        ),
        migrations.AddField(
            model_name='department',
            name='total_lecture_hours',
            field=models.PositiveIntegerField(default=0, editable=False, help_text='Total lecture hours assigned from all curricula'),
        ),
        migrations.AddField(
            model_name='department',
            name='total_practice_hours',
            field=models.PositiveIntegerField(default=0, editable=False, help_text='Total practice hours assigned from all curricula'),
        ),
        migrations.AddField(
            model_name='department',
            name='total_seminar_hours',
            field=models.PositiveIntegerField(default=0, editable=False, help_text='Total seminar hours assigned from all curricula'),
        ),
    ]
