# Generated by Django 5.2 on 2025-05-11 21:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
        ('departments', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='department',
            field=models.ForeignKey(blank=True, help_text='The department this user belongs to, if applicable.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='staff_members', to='departments.department'),
        ),
    ]
