# Generated by Django 5.1.7 on 2025-05-07 18:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Curriculum',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=20, unique=True)),
                ('title', models.CharField(max_length=255)),
                ('start_year', models.PositiveIntegerField()),
                ('degree', models.CharField(choices=[('Bachelors', 'Bachelors'), ('Masters', 'Masters')], max_length=20)),
                ('duration', models.PositiveIntegerField()),
                ('data', models.JSONField(blank=True, help_text='JSON data about mandatory and selective courses', null=True)),
            ],
            options={
                'verbose_name': 'Curriculum',
                'verbose_name_plural': 'Curricula',
                'ordering': ['title', 'start_year'],
            },
        ),
    ]
