# Generated by Django 5.1.7 on 2025-04-27 09:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('departments', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Professor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('employee_id', models.CharField(max_length=20, unique=True)),
                ('title', models.CharField(help_text='Academic title (e.g., Assistant Professor)', max_length=50)),
                ('employment_type', models.FloatField(choices=[(0.25, '0.25'), (0.5, '0.50'), (0.75, '0.75'), (1.0, '1.00'), (1.25, '1.25'), (1.5, '1.50'), (1.75, '1.75'), (2.0, '2.00')], default=1.0, help_text='Employment type (fraction of full-time)')),
                ('is_degree_holder', models.BooleanField(default=False, help_text='Whether the professor holds a doctoral degree')),
                ('department', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='professors', to='departments.department')),
                ('user', models.OneToOneField(limit_choices_to={'user_type__in': ['professor', 'department_head']}, on_delete=django.db.models.deletion.CASCADE, related_name='professor_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Professor',
                'verbose_name_plural': 'Professors',
                'ordering': ['user__last_name', 'user__first_name'],
            },
        ),
    ]
