# Generated by Django 5.1.7 on 2025-05-12 18:07

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('curricula', '0001_initial'),
        ('departments', '0002_department_total_laboratory_hours_and_more'),
        ('professors', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ProfessorLoad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course_code', models.CharField(blank=True, db_index=True, help_text='Code of the mandatory course from the curriculum.', max_length=50, null=True, verbose_name='Course Code (Mandatory)')),
                ('slot_number', models.IntegerField(blank=True, db_index=True, help_text='Slot number of the selective block from the curriculum.', null=True, verbose_name='Slot Number (Selective)')),
                ('course_title', models.CharField(help_text='Title of the course or description of the selective slot (for display).', max_length=255, verbose_name='Course/Slot Title')),
                ('academic_year', models.PositiveIntegerField(db_index=True, help_text='The starting year of the academic year (e.g., 2024 for 2024/2025).', verbose_name='Academic Year (Start)')),
                ('assigned_lecture_hours', models.PositiveIntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Assigned Lecture Hours')),
                ('assigned_practice_hours', models.PositiveIntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Assigned Practice Hours')),
                ('assigned_laboratory_hours', models.PositiveIntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Assigned Laboratory Hours')),
                ('assigned_seminar_hours', models.PositiveIntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Assigned Seminar Hours')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('curriculum', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='curriculum_loads', to='curricula.curriculum', verbose_name='Curriculum')),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='department_loads', to='departments.department', verbose_name='Department')),
                ('professor', models.ForeignKey(limit_choices_to={'user_type': 'professor'}, on_delete=django.db.models.deletion.CASCADE, related_name='assigned_loads', to=settings.AUTH_USER_MODEL, verbose_name='Professor')),
            ],
            options={
                'verbose_name': 'Professor Load Assignment',
                'verbose_name_plural': 'Professor Load Assignments',
                'ordering': ['academic_year', 'professor__last_name', 'course_title'],
                'indexes': [models.Index(fields=['department', 'academic_year'], name='professors__departm_2e82b7_idx')],
                'unique_together': {('professor', 'curriculum', 'course_code', 'academic_year'), ('professor', 'curriculum', 'slot_number', 'academic_year')},
            },
        ),
    ]
